from django.db import models
from django.contrib.auth.models import User

# ==========================================
# 1. AI & USER PROFILES
# ==========================================

class StudentProfile(models.Model):
    """
    Links to the default Django User model to store AI-specific data 
    without needing to write a Custom User Model.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    
    # This stores the user's "Knowledge State" as an array of numbers (e.g., [0.8, 0.2, 0.9])
    # MongoDB handles JSON/Arrays perfectly.
    learning_vector = models.JSONField(default=list, blank=True)
    completed_lessons = models.JSONField(default=list, blank=True)
    
    last_active_date = models.DateField(auto_now=True, null=True, blank=True)
    last_watched_lesson = models.ForeignKey('Lesson', on_delete=models.SET_NULL, null=True, blank=True)
    streak_count = models.IntegerField(default=0)
    
    def __str__(self):
        return f"{self.user.username}'s Profile"


# ==========================================
# 2. COURSE ARCHITECTURE (Normalized)
# ==========================================

class Course(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    instructor = models.CharField(max_length=100)
    thumbnail = models.URLField(blank=True)
    description = models.TextField(blank=True)
    
    # Stores the mathematical representation of what this course teaches
    # generated by Gemini's embedding model.
    course_embedding = models.JSONField(default=list, blank=True)

    raw_modules = models.TextField(db_column='modules', blank=True, null=True) 

    def __str__(self):
        return self.title

class Module(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='modules')
    title = models.CharField(max_length=255)
    order = models.PositiveIntegerField(default=0, help_text="Order of the module in the course")

    class Meta:
        ordering = ['order']
        verbose_name = "Course Chapter"
        verbose_name_plural = "Course Chapters"

    def __str__(self):
        return f"{self.course.title} - {self.title}"

class Lesson(models.Model):
    module = models.ForeignKey(Module, on_delete=models.CASCADE, related_name='lessons')
    title = models.CharField(max_length=255)
    video_url = models.URLField(blank=True)
    duration = models.CharField(max_length=10, blank=True, null=True, help_text="e.g., 11:31")
    content = models.TextField(blank=True, help_text="Text content or transcript for RAG AI")
    order = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['order']
        verbose_name = "Video Lesson"
        verbose_name_plural = "Video Lessons"

    def __str__(self):
        return self.title

# ==========================================
# 3. PROGRESS & QUIZZES
# ==========================================

class LessonProgress(models.Model):
    """Tracks exactly which videos/lessons a user has finished."""
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='progress')
    lesson = models.ForeignKey('Lesson', on_delete=models.CASCADE)
    is_completed = models.BooleanField(default=False)
    completed_at = models.DateTimeField(auto_now=True)
    time_spent_seconds = models.IntegerField(default=0)

    class Meta:
        unique_together = ('user', 'lesson') # Prevents duplicate progress entries
        verbose_name_plural = "Lesson_Progress"

    def __str__(self):
        return f"{self.user.username} - {self.lesson.title}"

class AIQuiz(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=255)
    topic = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    quiz_data = models.JSONField() 

    class Meta:
        verbose_name = "AI Generated Quiz" 
        # Plural name in the admin
        verbose_name_plural = "AI Generated Quizzes"

    def __str__(self):
        return self.title

class QuizResult(models.Model):
    # Linked to the user so we can update their StudentProfile.learning_vector
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    topic = models.CharField(max_length=200)
    score = models.IntegerField()
    total_questions = models.IntegerField()
    percentage = models.IntegerField()
    date_taken = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'Quizzes'

    def __str__(self):
        return f"{self.topic}: {self.score}/{self.total_questions}"