# Generated by Django 4.1.13 on 2026-03-26 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0006_aiquiz_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='last_active_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_watched_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_app.lesson'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='streak_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lesson_Progress',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
